version: "3.8"
services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db
  api:
    build: ./backend/api
    container_name: api_c
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo_db:27017
      - DB_NAME=my_db
    volumes:
      - ./backend/api:/api
      - ./backend/api/node_modules:/api/node_modules
volumes:
  mongo_db:
